### ISSUE TITLE
New tab opened adjacent to the existing tab?

### ISSUE THREAD

**Issue by prech** [vyang17/longPressNewTabClone#2]
Thanks much for cloning this extension over from Firefox

I wonder if there's an easy way to change the new tab such that it opens adjacent/right next to the parent tab? Right now it opens the new tab to the very far right.

Or if there's an easy way to edit some simple HTML/CSS parameter, I'd be glad to try myself if I knew the tag/parameter

**Comment by vyang17** [comment]
That's a good idea and [it seems like it is possible](https://developer.chrome.com/docs/extensions/reference/tabs/#method-create)! 

I'm not too familiar with js but can probably hack something together with the power of google and copy pasta. This also might take a few weeks since I'm going through a move atm.

**Comment by prech** [comment]
Any progress on this implementation, friend?

I emailed the Firefox creator a few times, also, but he didn't respond...

**Comment by prech** [comment]
Thanks much, @vyang17 

Is there any way to reverse the adjacent tab behavior such that the new tab is to the right of the open tab, rather than the left? Basically, to align with typical "Open link in new tab" behavior.

Much appreciated!

**Comment by vyang17** [comment]
@prech, to my knowledge it should be opening the new tab to the right of the current tab. Is it opening to the left for you?

**Comment by vyang17** [comment]
Interesting... I am using Vivaldi and the behavior is as expected - to the right. I just downloaded Chrome and now see what you mean by it opening on the left.

I will see what I can do, <strike>but the fix won't be out until maybe tomorrow.</strike>

**Comment by vyang17** [comment]
@prech , please download the latest and see if that works for you. Should be fixed in #5

**Comment by prech** [comment]
Thanks for the fast update, @vyang17!

It looks like new tabs are now opening to the right :)

Much appreciated
