### ISSUE TITLE
Manifest version 2 is deprecated, and support will be removed in 2023.

### ISSUE THREAD

**Issue by p3P4** [vyang17/longPressNewTabClone#7]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
{
    // Required
    "manifest_version": 2,
    "name": "Long Press New Tab",
    "version": "4.1",

    // Recommended
    "description": "Open links as background tabs by clicking links and holding",
    "icons": {
        "16": "img/icon16.png",

**Comment by ceedveed** [comment]
This is one of my must have extensions! Thanks for the notice and I hope the developer or others can provide a fix when January 2023 arrives.

> Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

**Comment by vyang17** [comment]
@p3P4 @ceedveed 

Extension has been updated to manifest version 3 through #8 .

Overall, this was a fairly big change, so there may be a few bugs, but core functionality should be the same.

**Comment by vyang17** [comment]
Now that I've been using it more, I'd say best to continue to use MV2 version until closer to the transition deadline.

IMO, this extension relies heavily on persistent background and MV3 at its current state does not allow that so sometimes it will not open new tab until the page refreshes.

**Comment by ceedveed** [comment]
Is it still recommended to use mv2 version? Are the issues with mv3 still present?

**Comment by vyang17** [comment]
@ceedveed 
Yes, I would recommend still using the MV2 version as it is still working perfectly for me. Google has pushed back MV2 deprecation timeline to TBD. And I've been pretty busy with work and life so haven't had the time to look more into MV3. 

I will support this extension to the best of my ability, as this is a feature I have used since the OG Opera days.

**Comment by prech** [comment]
Really appreciate the work on this project.

Glad that v5.0 still works with Manifest v3 when installed with the Zip file/Unpacked extension option
